export const PR2A_MUTATION_CONTROLS = Object.freeze({
  AC1: [
    'tooling-bootstrap-scope-violated',
    'planning-base-tree-mismatch',
    'planning-input-changed-without-replan',
    'tracked-file-omitted-from-denominator',
    'command-bearing-file-misclassified-non-executable',
    'executable-classification-incomplete',
    'reachable-helper-chain-missing',
    'target-independent-primitive-detection-bypassed',
    'reachable-unresolved-primitive-suppressed',
    'class1-through-class4b-row-omitted',
    'launch-guard-assertion-unclassified',
    'lifecycle-function-alias-effect-or-helper-omitted',
    'lifecycle-cli-branch-unclassified',
    'retain-read-only-row-interprets-policy',
    'legacy-operation-without-protocol-disposition',
    'overlap-unsafe-operation-not-quiesced',
    'unproven-operation-grouped-into-representative-class',
    'unsupported-retirement-selected',
    'implementation-operation-not-in-reviewed-plan',
  ],
  AC2: [
    'claim-namespace-or-key-changed',
    'persisted-path-or-schema-changed',
    'protocol-ordering-changed',
    'record-reread-under-exclusion-omitted',
    'generation-fence-weakened',
    'lock-loss-or-reacquisition-uses-cached-authority',
    'crash-point-breaks-single-authority',
    'legacy-record-class-unreadable',
    'identity-ambiguity-reclaimed',
    'policy-semantics-changed',
    'declared-reap-trigger-broken',
    'new-reaper-scheduler-added',
    'unsupported-boundary-accepted',
    'tracked-legacy-oracle-used',
    'protocol-matrix-duplicated-with-divergent-primitive',
  ],
  AC3: [
    'claimant-family-still-reaches-powershell-claim',
    'supported-lifecycle-unit-still-interprets-in-powershell',
    'supported-lifecycle-unit-still-mutates-in-powershell',
    'internal-lifecycle-helper-bypasses-disposition',
    'retain-read-only-unit-returns-policy-result',
    'cli-verb-bypasses-typescript-authority',
    'powershell-bridge-contains-policy-or-locking',
    'typescript-dispatches-to-powershell',
    'second-namespace-or-lock-tree-created',
    'operation-semantic-primitive-usage-test-missing',
    'operation-specific-durability-test-missing',
    'representative-overlap-class-missing',
    'external-root-reaches-target-internal-claim-unit',
  ],
  AC4: [
    'retired-guard-or-verifier-edge-remains',
    'surviving-launch-assertion-lost',
    'supervisor-reverse-edge-remains',
    'claim-reverse-edge-remains',
    'powershell-policy-unit-remains-reachable',
    'fleet-hygiene-surface-removed',
    'tracked-d928-execution-surface-remains',
    'final-tracked-file-classification-invalid',
    'command-bearing-primitive-hidden-by-non-executable-row',
    'final-unresolved-set-nonempty',
    'external-source-misreported-target-internal',
    'final-diff-does-not-equal-reviewed-operation-rows',
  ],
  AC5: [
    'receipt-final-tree-or-lineage-invalid',
    'planning-receipt-tooling-identity-mismatch',
    'receipt-self-asserts-unverifiable-tree',
    'receipt-final-invariant-incomplete',
    'overlap-harness-or-job-bytes-unbound',
    'overlap-operation-matrix-missing',
    'overlap-replay-command-missing',
    'candidate-build-not-derived-from-final-tree',
    'candidate-build-attestation-invalid',
    'overlap-evidence-generated-before-final-tree',
    'overlap-candidate-binding-mismatch',
    'receipt-generated-before-prerequisite-suites',
    'independent-pr2a-recompute-disagrees',
    '928-admission-skips-current-recompute',
    '928-admission-accepts-unsafe-current-invariants',
    '928-admission-requires-historical-inventory-equality',
    '928-admission-rejects-compatible-unrelated-evolution',
  ],
  AC6: [
    'bootstrap-contains-semantic-migration',
    'd928-change-detected',
    'powershell-file-added',
    'powershell-policy-or-supervisor-logic-added',
    'powershell-compatibility-clone-added',
    'typescript-to-powershell-claim-dispatch-added',
    'tracked-d928-oracle-added',
    'new-scheduler-or-reaper-surface-added',
    'retirement-outside-closed-list',
    'path-or-operation-outside-reviewed-declaration',
    'allowed-roots-or-denylist-violation',
    'rename-copy-symlink-gitlink-or-mode-evasion',
    'test-lane-classification-invalid',
  ],
  AC7: [
    'shared-protocol-interleaving-class-fails',
    'representative-end-to-end-class-fails',
    'process-ordering-substitutes-for-persisted-exclusion',
    'reaper-or-release-mutates-replacement-generation',
    'declared-reap-trigger-unreachable',
    'partial-tree-state-silently-supported',
    'ci-isolation-or-reentry-broken',
    'rollback-cross-version-gate-not-existing-or-not-shared',
    'rollback-quiescence-inventory-incomplete',
    'rollback-entry-resumes-before-zero-survivors',
    'rollback-detached-drain-artifact-invalid',
    'rollback-rehearsal-in-evidence-checkout',
    'rollback-imports-928-activation-machinery',
    'unsupported-platform-or-filesystem-operation-succeeds',
  ],
  AC8: [
    'mandatory-command-or-lane-fails',
    'mandatory-test-suppressed-or-reduced',
    'final-evidence-tree-or-platform-stale',
    'required-suite-omitted-from-mandatory-path',
    'receipt-dependent-suite-evidenced-pre-receipt',
    'overlap-evidence-candidate-tree-mismatch',
    'receipt-and-final-verification-tree-differ',
    'final-checks-on-dirty-worktree',
    'evidence-tree-differs-from-executed-bytes',
    'implementation-change-reruns-tail-only',
    'planning-change-preserves-stale-ac1',
    'same-tree-sha-change-rejected-as-tree-mismatch',
    'external-928-sync-evidence-missing',
  ],
} as const);

export type Pr2aAcceptanceId = keyof typeof PR2A_MUTATION_CONTROLS;
export type Pr2aMutationId = (typeof PR2A_MUTATION_CONTROLS)[Pr2aAcceptanceId][number];

export interface Pr2aMutationBinding {
  ac: Pr2aAcceptanceId;
  mutationId: Pr2aMutationId;
  failingTestId: string;
}

const PLANNING_VALIDATOR_MUTATIONS = new Set<string>([
  ...PR2A_MUTATION_CONTROLS.AC1.map((id) => `AC1:${id}`),
  'AC4:fleet-hygiene-surface-removed',
  'AC4:final-tracked-file-classification-invalid',
  'AC4:command-bearing-primitive-hidden-by-non-executable-row',
  'AC4:final-unresolved-set-nonempty',
  'AC4:external-source-misreported-target-internal',
  'AC4:final-diff-does-not-equal-reviewed-operation-rows',
  'AC5:planning-receipt-tooling-identity-mismatch',
  'AC6:bootstrap-contains-semantic-migration',
  'AC6:d928-change-detected',
  'AC6:powershell-file-added',
  'AC6:retirement-outside-closed-list',
  'AC6:path-or-operation-outside-reviewed-declaration',
  'AC6:allowed-roots-or-denylist-violation',
  'AC6:rename-copy-symlink-gitlink-or-mode-evasion',
]);

export const PR2A_MUTATION_CATALOG: readonly Pr2aMutationBinding[] = Object.freeze(
  Object.entries(PR2A_MUTATION_CONTROLS).flatMap(([ac, ids]) => ids.map((mutationId) => {
    const key = `${ac}:${mutationId}`;
    return {
      ac: ac as Pr2aAcceptanceId,
      mutationId,
      failingTestId: PLANNING_VALIDATOR_MUTATIONS.has(key)
        ? 'pr2a:planning-validator'
        : `mutation-contract:${key}`,
    };
  })),
);
