export const REVIEW_RECOVERY_SCHEMA_VERSION: number;
export const DEFAULT_CRASH_GRACE_MS: number;
export const DEFAULT_MAX_REVIEW_DURATION_MS: number;
export const DEFAULT_AMBIGUOUS_STALE_MS: number;
export const RECOVERY_TERMINAL_STATUS: string;
export const RECOVERY_REASON_PROVABLY_DEAD: string;
export const RECOVERY_REASON_AMBIGUOUS_STALE: string;
export const RECOVERY_REASON_LEGACY_AMBIGUOUS: string;
export const RECOVERY_TERMINATION_REASONS: Set<string>;
export const NON_TERMINAL_REVIEW_STATUSES: Set<string>;
export const TERMINAL_REVIEW_STATUSES: Set<string>;

export function resolveRecoveryConfig(config?: Record<string, unknown>, env?: Record<string, string | undefined>): Record<string, number>;
export function validateRecoveryConfig(config?: Record<string, number>): { ok: boolean; errors: string[] };
export function classifyReviewStatus(status: unknown): 'non_terminal' | 'terminal' | 'unknown';
export function fingerprintRun(run: Record<string, unknown>): string;
export function getAoProjectDir(projectId: string, baseDir?: string): string;
export function getCodeReviewStoreDir(projectId: string, options?: Record<string, unknown>): string;
export function readRunRecords(storeDir: string): Array<{ path: string; run: Record<string, unknown> }>;
export function getSidecarDir(storeDir: string): string;
export function getRecoveryStatePath(storeDir: string): string;
export function getRecoveryAuditPath(storeDir: string): string;
export function readRecoveryState(storeDir: string): Record<string, unknown>;
export function writeRecoveryState(storeDir: string, state: Record<string, unknown>): void;
export function classifyReviewerLiveness(sidecar: Record<string, unknown> | null, options?: Record<string, unknown>): { outcome: 'alive' | 'provably_not_alive' | 'ambiguous'; reason: string };
export function evaluateRecoveryForRun(input: Record<string, unknown>): Record<string, unknown>;
export function terminalizeRunRecord(input: Record<string, unknown>): { ok: boolean; reason?: string; status?: string; error?: string; run?: Record<string, unknown> };
export function runRecoveryTick(input?: Record<string, unknown>): Record<string, unknown>;
export function findRunForReviewerSession(storeDir: string, reviewerSessionId: string): { path: string; run: Record<string, unknown> } | null;
export function captureReviewerLiveness(input: Record<string, unknown>): { ok: boolean; reason?: string; runId?: string; path?: string };
